# nome da pipeline
name: Run Basic Testes

# em que omento será executada 
on: 
  pull_request: 
      branches:  [master]

jobs:
    # o que vai ser feito nessa pipeline
    # só teremos um job, rodar os testes
    cypress-run:
        # em que máquina que sera executado o teste
        runs-on: ubuntu-latest

        # passo a passo para rodar os testes
        steps:
            # clone do projeto
            - name: Checkout/Clone do projeto
              uses: actions/checkout@v3
            
            # exemplo de execução no terminal
            - name: instalar dependencias do projeto
              run: npm install

        # instala o node também, execução e config do projeto
            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                record: true
              env:
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

